# Generated by Django 5.2.12 on 2026-05-01 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('no_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jadwal', models.CharField(blank=True, max_length=200, null=True)),
                ('poli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokter', to='antrian.poli')),
            ],
        ),
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('nomor_antrian', models.IntegerField()),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Diperiksa', 'Diperiksa'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], default='Menunggu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antrian.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antrian', to='antrian.pasien')),
                ('poli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antrian.poli')),
            ],
            options={
                'ordering': ['tanggal', 'poli', 'nomor_antrian'],
                'unique_together': {('poli', 'tanggal', 'nomor_antrian')},
            },
        ),
    ]
