# Generated by Django 5.2.12 on 2026-05-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrian',
            name='waktu_kunjungan',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='no_rekam_medis',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='antrian',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
