# Generated by Django 6.0.5 on 2026-05-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0002_antrian_waktu_kunjungan_pasien_no_rekam_medis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrian',
            name='keluhan_singkat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
